name: flowbot_history_tformer
data_dir: ${oc.env:HOME}/datasets/partnet-mobility

dataset: umpnet
model: flowbot_history_tformer
batch_size: 64
lr: 1e-3
mask_input_channel: True
randomize_camera: True
seed: 42
